name: CI

on: push

jobs:
  php-tests:

    strategy:
      matrix:
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
        prefer: [ 'lowest', 'stable' ]

    name: Test on PHP ${{ matrix.php }} with ${{ matrix.prefer }} composer prefer option
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Check PHP Version
        run: php -v

      - uses: "ramsey/composer-install@v1"

      - name: Run tests
        run: composer test

      - name: Run PHPStan
        run: vendor/bin/phpstan

  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1

      - uses: "ramsey/composer-install@v1"

      - name: Lint Code
        uses: github/super-linter@v3
        env:
          FILTER_REGEX_EXCLUDE: .*vendor.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PHP_PSALM: false
